    window.KLYZE_SSS = [
      { id: "overlay-gorunmuyor", kat: "teknik", etiket: "overlay gorunmuyor gozukmuyor ctrl k oyun ici",
        baslik: "Overlay oyunda gÃ¶rÃ¼nmÃ¼yor",
        ozet: "Ctrl+K Ã§alÄ±ÅŸmÄ±yorsa Ã¶nce yÃ¶netici izni ve oyun modunu kontrol et.",
        adimlar: ["Klyze'yi kapatÄ±p saÄŸ tÄ±k > YÃ¶netici olarak Ã§alÄ±ÅŸtÄ±r ile aÃ§.", "Valorant'ta tam ekran yerine Tam Ekran Pencereli (borderless) moda geÃ§.", "Ayarlar > Overlay bÃ¶lÃ¼mÃ¼nden kÄ±sayolu deÄŸiÅŸtirip tekrar dene.", "Sorun sÃ¼rerse Destek sayfasÄ±ndan ekran gÃ¶rÃ¼ntÃ¼sÃ¼yle talep aÃ§."] },
      { id: "smartscreen-uyarisi", kat: "kurulum", etiket: "kurulum smartscreen bilinmeyen yayimci windows korudu calistir",
        baslik: "Windows 'bilinmeyen yayÄ±mcÄ±' uyarÄ±sÄ± veriyor",
        ozet: "Ä°mza sertifikamÄ±z yeni olduÄŸu iÃ§in SmartScreen ilk sÃ¼rÃ¼mlerde uyarÄ±r.",
        adimlar: ["UyarÄ± ekranÄ±nda Ek bilgi'ye tÄ±kla.", "Yine de Ã§alÄ±ÅŸtÄ±r'Ä± seÃ§.", "Kurulum normal devam eder. Sertifika itibarÄ± arttÄ±kÃ§a bu uyarÄ± kalkar."] },
      { id: "google-giris-hatasi", kat: "hesap", etiket: "google giris yapamiyorum hata oturum login hesap",
        baslik: "Google ile giriÅŸ yapamÄ±yorum",
        ozet: "Genelde tarayÄ±cÄ± Ã§erezleri veya eski oturum neden olur.",
        adimlar: ["TarayÄ±cÄ±da gizli pencere aÃ§Ä±p tekrar dene.", "Google hesabÄ±nda Ã¼Ã§Ã¼ncÃ¼ parti eriÅŸimlerine izinli olduÄŸunu kontrol et.", "Destek sayfasÄ±ndan giriÅŸ yapÄ±p talep aÃ§arsan hesabÄ±na bakalÄ±m."] },
      { id: "maclar-guncellenmiyor", kat: "teknik", etiket: "mac rank guncellenmiyor gozukmuyor analiz veri riot",
        baslik: "MaÃ§larÄ±m / rankÄ±m gÃ¼ncellenmiyor",
        ozet: "Riot verisi birkaÃ§ dakikaya kadar gecikebilir.",
        adimlar: ["Riot ID ve tag bilginin doÄŸru yazÄ±ldÄ±ÄŸÄ±ndan emin ol.", "10 dakika bekleyip Analiz sayfasÄ±nÄ± yenile.", "HÃ¢lÃ¢ yoksa hangi maÃ§Ä±n eksik olduÄŸunu yazarak talep aÃ§."] },
      { id: "destek-talebi-nasil", kat: "destek", etiket: "destek talebi acma dosya gorsel video durum takip",
        baslik: "Destek talebi nasÄ±l aÃ§Ä±lÄ±r?",
        ozet: "Google ile giriÅŸ yap, konunu yaz, gÃ¶rsel/video ekle.",
        adimlar: ["Destek sayfasÄ±nda Google ile giriÅŸ yap.", "Kategori seÃ§, konuyu ve aÃ§Ä±klamayÄ± yaz.", "En fazla 3 gÃ¶rsel/video ekle (her biri 25MB).", "Taleplerim bÃ¶lÃ¼mÃ¼nden durumunu ve ekibin yanÄ±tÄ±nÄ± takip et."] },
      { id: "canli-mac-yavas", kat: "teknik", etiket: "canli mac yavas gec geliyor takip asistan",
        baslik: "CanlÄ± maÃ§ takibi yavaÅŸ geliyor",
        ozet: "MaÃ§ baÅŸlangÄ±cÄ±nda 1-2 dakikalÄ±k gecikme normaldir.",
        adimlar: ["MaÃ§Ä±n ilk dakikalarÄ±nda verinin oturmasÄ±nÄ± bekle.", "Ä°nternet baÄŸlantÄ±nÄ± kontrol et.", "SÃ¼rekli 5 dakikadan uzunsa talep aÃ§."] },
      { id: "yorum-gorunmuyor", kat: "topluluk", etiket: "yorum gorunmuyor yayinlanmadi begeni yanit",
        baslik: "Yorumum gÃ¶rÃ¼nmÃ¼yor",
        ozet: "Yorum yazmak iÃ§in giriÅŸ yapman gerekir.",
        adimlar: ["Google ile giriÅŸ yaptÄ±ÄŸÄ±ndan emin ol.", "SayfayÄ± yenile.", "KÃ¼fÃ¼r/hakaret iÃ§eren yorumlar gizlenir."] },
      { id: "klyzeac-nedir", kat: "guvenlik", etiket: "klyzeac anti cheat hile koruma guvenlik nedir",
        baslik: "KlyzeAC nedir?",
        ozet: "Topluluk gÃ¼venliÄŸini koruyan arka plan bileÅŸenidir.",
        adimlar: ["Klyze aÃ§Ä±ldÄ±ÄŸÄ±nda otomatik baÅŸlar, ayrÄ±ca kurmana gerek yok.", "KiÅŸisel dosyalarÄ±na dokunmaz, yalnÄ±zca oyun oturumunu izler.", "Kapatmak istersen Klyze'yi kapatman yeterli."] },
      { id: "kaldirma", kat: "kurulum", etiket: "kaldirma silme uninstall nasil silinir",
        baslik: "Klyze nasÄ±l kaldÄ±rÄ±lÄ±r?",
        ozet: "BaÅŸlat menÃ¼sÃ¼nden tek tÄ±kla silinir.",
        adimlar: ["BaÅŸlat menÃ¼sÃ¼nde Klyze'yi KaldÄ±r'a tÄ±kla.", "Ayarlar > Uygulamalar > Klyze > KaldÄ±r da olur.", "KlasÃ¶r ve ayarÄ±n tamamen temizlenir."] },
      { id: "sifre-sifirlama", kat: "hesap", etiket: "sifre unuttum sifirlama kurtarma hesap riot",
        baslik: "HesabÄ±mÄ± kaybettim / ÅŸifremi unuttum",
        ozet: "Klyze'nin ayrÄ± ÅŸifresi yok; Google hesabÄ±nla girersin.",
        adimlar: ["Google ÅŸifreni sÄ±fÄ±rla, sonra tekrar dene.", "Riot hesabÄ±nla ilgili sorunlarda Riot Destek'e baÅŸvur.", "Klyze verilerin iÃ§in Destek sayfasÄ±ndan yaz."] }
    ];
